//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJETIVO
    {
        public int ObjetivoId { get; set; }
        public int FkTipoObjetivoId { get; set; }
        public int FkPersonaId { get; set; }
        public System.DateTime ObjetivoFechaInicio { get; set; }
        public System.DateTime ObjetivoFechaFin { get; set; }
        public string ObjetivoDescripcion { get; set; }
        public bool ObjetivoCompleto { get; set; }
        public decimal ObjetivoValor { get; set; }
        public System.DateTime ObjetivoFechaModificacion { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual TIPOOBJETIVO TIPOOBJETIVO { get; set; }
    }
}
