//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONE
    {
        public int TransaccionId { get; set; }
        public string TransaccionDescripcion { get; set; }
        public decimal TransaccionValor { get; set; }
        public System.DateTime TransaccionFecha { get; set; }
        public System.DateTime TransaccionFechaModificacion { get; set; }
        public int FkIdPersona { get; set; }
        public Nullable<int> FkIdComercio { get; set; }
        public int FkIdComprobante { get; set; }
        public int FkIdTipoTransaccion { get; set; }
    
        public virtual COMERCIO COMERCIO { get; set; }
        public virtual COMPROBANTE COMPROBANTE { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual TIPOTRANSACCION TIPOTRANSACCION { get; set; }
    }
}
