SELECT * FROM PERSONAS

SELECT * FROM LOGINS
INSERT INTO LOGINS VALUES ('Francisco','12345')


INSERT INTO Roles VALUES ('Administrador')
INSERT INTO Roles VALUES ('Usuario')
SELECT * FROM Roles


INSERT INTO LOGINSInROLES VALUES(8,2)
SELECT * FROM LOGINSInROLES

